version: '3.8'

services:
  app:
    build: .
    ports:
      - "12800:12800"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=11111111
      - MYSQL_DB=mydb
    volumes:
      - ./kubeconfig.yaml:/app/kubeconfig.yaml
      - ./templates:/app/templates

  mysql:
    image: mysql:5.8
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
    volumes:
      - /app/status-x/mysqlDate:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
